
const APPS_SCRIPT_URL='https://script.google.com/macros/s/AKfycby6jTm5xQmcQAUjdaubsOWOn7Xws4UWjV9uWbOExlEQArCSN6hubMt3U128QjmlWZP0Ow/exec';
const ROOT_FOLDER_ID='1NZfDp_9SU50OVDJXLuTcGZNj5JvSdpdX';
const CACHE_KEY='payslip_bip_list_cache_v14';
const pdfjsLib=globalThis.pdfjsLib||window.pdfjsLib;
if(pdfjsLib) pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
const state={years:[],periods:[],records:[],filteredRecords:[],selectedYear:'',selectedPeriod:'',selectedRecord:null,previewBytes:null,pdfDoc:null,zoom:1.2,searchIndex:-1,isRefreshing:false,printFrame:null};
const el={yearSelect:document.getElementById('yearSelect'),periodSelect:document.getElementById('periodSelect'),searchInput:document.getElementById('searchInput'),searchResults:document.getElementById('searchResults'),refreshBtn:document.getElementById('refreshBtn'),printBtn:document.getElementById('printBtn'),pdfContainer:document.getElementById('pdfContainer'),statusText:document.getElementById('statusText'),fileNameText:document.getElementById('fileNameText'),employeeIdText:document.getElementById('employeeIdText'),employeeNameText:document.getElementById('employeeNameText'),pageInfo:document.getElementById('pageInfo')};
function setStatus(t){if(el.statusText) el.statusText.textContent=t;}
function setDbState(s,t){const w=document.getElementById('dbStatusWrap');const x=document.getElementById('dbStatusText');if(w) w.dataset.state=s;if(x) x.textContent=t;}
function apiUrl(action,params={}){const url=new URL(APPS_SCRIPT_URL);url.searchParams.set('action',action);url.searchParams.set('rootFolderId',ROOT_FOLDER_ID);Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='') url.searchParams.set(k,v)});return url.toString();}
async function apiGet(action,params={},timeoutMs=10000){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{const res=await fetch(apiUrl(action,params),{cache:'no-store',redirect:'follow',signal:controller.signal});const text=await res.text();if(!res.ok) throw new Error(`HTTP ${res.status}`);const json=JSON.parse(text);if(json.ok===false) throw new Error(json.message||'Request gagal');return json;}finally{clearTimeout(timer);}}
function parseBase64(base64){const b=atob(base64);const bytes=new Uint8Array(b.length);for(let i=0;i<b.length;i++) bytes[i]=b.charCodeAt(i);return bytes;}
function extractYear(text){const m=String(text||'').match(/\b(20\d{2})\b/);return m?m[1]:'';}
function normalizeState(){state.records=(state.records||[]).map(r=>({...r,year:String(r.year||extractYear(r.periodLabel)||extractYear(r.fileName)||'')}));if(!state.years.length) state.years=[...new Set(state.records.map(r=>r.year).filter(Boolean))].sort();if(!state.selectedYear||!state.years.includes(state.selectedYear)) state.selectedYear=state.years[state.years.length-1]||'';state.periods=[...new Set(state.records.filter(r=>!state.selectedYear||String(r.year)===String(state.selectedYear)).map(r=>r.periodLabel).filter(Boolean))].sort();if(!state.periods.includes(state.selectedPeriod)) state.selectedPeriod=state.periods[0]||'';}
function renderSelectors(){if(el.yearSelect){el.yearSelect.innerHTML=state.years.map(y=>`<option value="${y}">${y}</option>`).join('');el.yearSelect.value=state.selectedYear||'';}if(el.periodSelect){el.periodSelect.innerHTML=state.periods.map(p=>`<option value="${p}">${p}</option>`).join('');el.periodSelect.value=state.selectedPeriod||'';}}
function getDisplayId(r){const m=String(r?.employeeId||r?.fileName||'').toUpperCase().match(/\bSR[0-9]{5,}\b/);return m?m[0]:String(r?.employeeId||'');}
function getDisplayName(r){return String(r?.employeeName||'').trim();}
function syncMeta(){const r=state.selectedRecord;if(el.fileNameText) el.fileNameText.textContent=r?.fileName||'-';if(el.employeeIdText) el.employeeIdText.textContent=getDisplayId(r)||'-';if(el.employeeNameText) el.employeeNameText.textContent=getDisplayName(r)||'-';}
async function fetchYearData(year,force=false){setDbState('loading','Menghubungkan database...');setStatus(force?`Menyegarkan ${year||'semua tahun'}...`:`Memuat data ${year||'terbaru'}...`);const json=await apiGet('list',{year:year,forceRefresh:force?'1':''},force?45000:10000);state.years=json.years||[];state.selectedYear=json.selectedYear||year||state.selectedYear;state.records=json.files||[];normalizeState();renderSelectors();setDbState('connected','Terhubung');setStatus(`Daftar ${state.selectedYear||'-'} siap • ${state.records.length} file`);}
async function serverSearch(q){q=String(q||'').trim();if(!q){state.filteredRecords=[];renderSearch();return;}const json=await apiGet('search',{q:q,year:state.selectedYear},12000);state.filteredRecords=json.files||[];state.searchIndex=0;renderSearch();}
function renderSearch(){if(!el.searchResults) return;const rows=state.filteredRecords||[];if(!rows.length){el.searchResults.innerHTML='';el.searchResults.classList.add('hidden');return;}el.searchResults.innerHTML=rows.map((r,i)=>`<div class="search-item ${i===state.searchIndex?'active':''}" data-index="${i}"><div class="search-item-title">${getDisplayId(r)} - ${getDisplayName(r)}</div><div class="search-item-sub">${r.periodLabel||'-'} • ${r.year||'-'}</div></div>`).join('');el.searchResults.classList.remove('hidden');}
function hideSearch(){el.searchResults?.classList.add('hidden');}
async function loadPdfBytes(bytes){state.previewBytes=bytes;const doc=await pdfjsLib.getDocument({data:bytes}).promise;state.pdfDoc=doc;const page=await doc.getPage(1);const cssViewport=page.getViewport({scale:state.zoom});const renderViewport=page.getViewport({scale:state.zoom*Math.min(2.2,Math.max(1.5,window.devicePixelRatio||1.5))});const wrap=document.createElement('div');wrap.className='page-wrap';wrap.style.width=`${cssViewport.width}px`;wrap.style.height=`${cssViewport.height}px`;const canvas=document.createElement('canvas');canvas.className='page-canvas';canvas.width=Math.floor(renderViewport.width);canvas.height=Math.floor(renderViewport.height);canvas.style.width=`${cssViewport.width}px`;canvas.style.height=`${cssViewport.height}px`;await page.render({canvasContext:canvas.getContext('2d',{alpha:false}),viewport:renderViewport}).promise;if(el.pdfContainer){el.pdfContainer.innerHTML='';wrap.appendChild(canvas);el.pdfContainer.appendChild(wrap);}if(el.pageInfo) el.pageInfo.textContent=`Page 1 / ${doc.numPages}`;}
async function loadRecord(r){state.selectedRecord=r;syncMeta();setStatus('Mengambil PDF asli...');const json=await apiGet('file',{fileId:r.fileId},12000);await loadPdfBytes(parseBase64(json.base64));setStatus('Preview PDF asli siap');}
async function pickRecord(index){const r=state.filteredRecords[index];if(!r) return; if(String(r.year||'')!==String(state.selectedYear)){await fetchYearData(r.year,false);} state.selectedPeriod=r.periodLabel||state.selectedPeriod;normalizeState();renderSelectors();if(el.searchInput) el.searchInput.value=`${getDisplayId(r)} - ${getDisplayName(r)}`;hideSearch();await loadRecord(r);}
async function printCurrent(){const bytes=state.previewBytes;if(!bytes||!bytes.length){setStatus('PDF belum siap untuk dicetak');return;}const blob=new Blob([bytes],{type:'application/pdf'});const url=URL.createObjectURL(blob);const iframe=document.createElement('iframe');Object.assign(iframe.style,{position:'fixed',right:'0',bottom:'0',width:'1px',height:'1px',border:'0',opacity:'0'});iframe.onload=()=>{const win=iframe.contentWindow;if(win){setTimeout(()=>{try{win.focus();win.print();setStatus('Dialog print dibuka');}catch{}},700);}setTimeout(()=>{URL.revokeObjectURL(url);iframe.remove();},15000);};document.body.appendChild(iframe);iframe.src=url;}
function bind(){el.yearSelect?.addEventListener('change',async()=>{state.selectedYear=el.yearSelect.value;state.selectedPeriod='';await fetchYearData(state.selectedYear,false);});el.periodSelect?.addEventListener('change',()=>{state.selectedPeriod=el.periodSelect.value;});el.searchInput?.addEventListener('input',()=>serverSearch(el.searchInput.value));el.searchInput?.addEventListener('focus',()=>serverSearch(el.searchInput.value));el.searchInput?.addEventListener('keydown',async(e)=>{if(el.searchResults?.classList.contains('hidden')) return;const max=state.filteredRecords.length-1;if(e.key==='ArrowDown'){e.preventDefault();state.searchIndex=Math.min(max,state.searchIndex+1);renderSearch();}else if(e.key==='ArrowUp'){e.preventDefault();state.searchIndex=Math.max(0,state.searchIndex-1);renderSearch();}else if(e.key==='Enter'){e.preventDefault();if(state.searchIndex>=0) await pickRecord(state.searchIndex);}else if(e.key==='Escape'){hideSearch();}});el.searchResults?.addEventListener('mousedown',async(e)=>{const item=e.target.closest('.search-item');if(!item) return;await pickRecord(Number(item.dataset.index));});document.addEventListener('click',(e)=>{if(!e.target.closest('.search-field')) hideSearch();});el.refreshBtn?.addEventListener('click',async()=>{await fetchYearData(state.selectedYear||'',true);});el.printBtn?.addEventListener('click',printCurrent);}
async function init(){bind();await fetchYearData('',false);const first=state.records[0];if(first) await loadRecord(first);}
init();
